version: '3.9'
services:
  postgrespr:
    image: postgres:14-alpine
    restart: unless-stopped
    ports:
      - 5456:5432
#    volumes:
#      - /Users/dinsaren/Desktop/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - "POSTGRES_HOST_AUTH_METHOD=trust"